namespace Iso8583Toolkit.IsoCore.Domain;

/// <summary>
/// Outcome of a parse attempt that surfaces partial progress on failure.
/// Returned by <see cref="Parsing.IsoParser.TryParse(string)"/> so the API can
/// show the user "we got this far, then it broke here" instead of dropping
/// every successfully parsed field on the floor.
/// </summary>
public sealed class IsoParseResult
{
    public bool Success { get; init; }

    /// <summary>Fully parsed message when <see cref="Success"/> is <c>true</c>.</summary>
    public IsoMessage? Message { get; init; }

    /// <summary>Error details when <see cref="Success"/> is <c>false</c>.</summary>
    public IsoParseError? Error { get; init; }

    /// <summary>
    /// Fields parsed before the failure. Empty when the parse succeeded or when
    /// the failure happened before any field was read.
    /// </summary>
    public IReadOnlyList<ParsedField> PartialFields { get; init; } = [];
}

public sealed class IsoParseError
{
    /// <summary>Where the failure happened (e.g. "MTI", "Bit 36").</summary>
    public required string Field { get; init; }

    /// <summary>Byte offset (binary wire) or char offset (ASCII wire) of the failure.</summary>
    public int Position { get; init; }

    /// <summary>Human-readable failure description.</summary>
    public required string Message { get; init; }

    /// <summary>Debug hint generated by the parser. Currently set when the failure
    /// happens inside the field-parsing loop, suggesting offset drift from a
    /// prior LL/LLL/LLLL field with wrong length.</summary>
    public string? Hint { get; init; }
}

public sealed class ParsedField
{
    public int BitNumber { get; init; }
    public required string Name { get; init; }
    public required string RawValue { get; init; }
}
