namespace Iso8583Toolkit.Cryptography.Tlv;

public sealed record TlvTagInfo(string Tag, string Name, string Description);

public static class EmvTagRegistry
{
    private static readonly Dictionary<string, TlvTagInfo> Tags = new(StringComparer.OrdinalIgnoreCase)
    {
        // ── Request tags (0100/0200 — sent by terminal) ─────────────────────
        ["9F26"] = new("9F26", "Application Cryptogram", "ARQC/TC/AAC cryptogram (8 bytes)"),
        ["9F27"] = new("9F27", "Cryptogram Information Data", "80=ARQC, 40=TC, 00=AAC"),
        ["9F10"] = new("9F10", "Issuer Application Data", "Proprietary data from ICC to issuer"),
        ["9F37"] = new("9F37", "Unpredictable Number", "Random number generated by terminal"),
        ["9F36"] = new("9F36", "Application Transaction Counter", "ATC maintained by ICC"),
        ["9F02"] = new("9F02", "Amount Authorized", "Authorized amount in BCD"),
        ["9F03"] = new("9F03", "Amount Other", "Cashback or other amount in BCD"),
        ["9F1A"] = new("9F1A", "Terminal Country Code", "ISO 3166 country code"),
        ["5F2A"] = new("5F2A", "Transaction Currency Code", "ISO 4217 currency code"),
        ["9A"]   = new("9A",   "Transaction Date", "YYMMDD in BCD"),
        ["9C"]   = new("9C",   "Transaction Type", "00=purchase, 01=cash, 09=cashback"),
        ["95"]   = new("95",   "Terminal Verification Results", "TVR 5 bytes"),
        ["82"]   = new("82",   "Application Interchange Profile", "AIP 2 bytes"),
        ["9F34"] = new("9F34", "CVM Results", "Cardholder Verification Method results"),
        ["9F33"] = new("9F33", "Terminal Capabilities", "Terminal capability flags"),
        ["9F35"] = new("9F35", "Terminal Type", "Terminal environment type"),
        ["9F09"] = new("9F09", "Application Version Number (Terminal)", "Terminal app version"),
        ["9F41"] = new("9F41", "Transaction Sequence Counter", "Terminal sequence counter"),
        ["84"]   = new("84",   "Dedicated File Name", "AID of the application"),
        ["4F"]   = new("4F",   "Application Identifier (AID)", "Application identifier"),
        ["50"]   = new("50",   "Application Label", "Application preferred name"),
        ["57"]   = new("57",   "Track 2 Equivalent Data", "Track 2 data from chip"),
        ["5A"]   = new("5A",   "Application PAN", "PAN from chip"),
        ["5F34"] = new("5F34", "PAN Sequence Number", "Distinguishes cards with same PAN"),
        ["8E"]   = new("8E",   "CVM List", "Cardholder Verification Method list"),
        ["9F08"] = new("9F08", "Application Version Number (ICC)", "ICC app version"),
        ["9F0D"] = new("9F0D", "Issuer Action Code - Default", "IAC Default"),
        ["9F0E"] = new("9F0E", "Issuer Action Code - Denial", "IAC Denial"),
        ["9F0F"] = new("9F0F", "Issuer Action Code - Online", "IAC Online"),
        ["9F6C"] = new("9F6C", "Mag Stripe Application Version Number", "MSD version"),
        ["9F6B"] = new("9F6B", "Track 2 Data", "Track 2 data for MSD"),

        // ── Response tags (0110/0210 — sent by issuer) ──────────────────────
        ["91"]   = new("91",   "Issuer Authentication Data", "ARPC (8 bytes) + optional Issuer Auth Code"),
        ["8A"]   = new("8A",   "Authorization Response Code", "2-byte ASCII response code"),
        ["71"]   = new("71",   "Issuer Script Template 1", "Scripts executed BEFORE TC generation"),
        ["72"]   = new("72",   "Issuer Script Template 2", "Scripts executed AFTER TC generation"),
        ["9F18"] = new("9F18", "Issuer Script Identifier", "Unique script identifier (4 bytes)"),
    };

    public static TlvTagInfo? GetInfo(string tag) =>
        Tags.GetValueOrDefault(tag.ToUpperInvariant());

    public static string GetName(string tag) =>
        GetInfo(tag)?.Name ?? $"Unknown ({tag})";

    public static string GetDescription(string tag) =>
        GetInfo(tag)?.Description ?? "";

    public static string InterpretCryptogramType(string cid) =>
        cid.ToUpperInvariant() switch
        {
            "80" => "ARQC",
            "40" => "TC",
            "00" => "AAC",
            _ => $"Unknown ({cid})"
        };
}
