using System.ComponentModel;
using Iso8583Toolkit.Cryptography.Emv;
using Iso8583Toolkit.Cryptography.Tlv;

namespace Iso8583Toolkit.Api.DTOs;

// ── Requests ────────────────────────────────────────────────────────────────

public sealed record ParseBit55Request(
    [property: Description("Hex bytes of the Bit 55 BER-TLV blob — e.g. \"9F2608…9F2701…9F1008…\".")]
    string HexBit55,
    [property: Description("Bytes of proprietary header to skip before the TLV stream (some acquirers prepend a length byte).")]
    int HeaderBytes = 0);

public sealed record ValidateArqcRequest(
    string HexBit55,
    string IssuerMasterKey,
    string Pan,
    string PanSequenceNumber,
    string Profile);

public sealed record GenerateArqcRequest(
    [property: Description("Issuer Master Key as 32 hex chars (16 bytes / Single-length 3DES).")]
    string IssuerMasterKey,
    [property: Description("PAN (13–19 digits).")] string Pan,
    [property: Description("PAN Sequence Number, 2 hex chars (e.g. \"00\").")] string PanSequenceNumber,
    [property: Description("Application Transaction Counter, 4 hex chars (e.g. \"001E\").")] string Atc,
    [property: Description("Amount Authorized — Bit 9F02, 12 hex chars zero-padded (cents).")] string AmountAuthorized,
    [property: Description("Amount Other — Bit 9F03, 12 hex chars zero-padded (cents).")] string AmountOther,
    [property: Description("Terminal Country Code — ISO 3166-1 numeric, 4 hex chars (e.g. \"0076\" = Brazil).")] string TerminalCountryCode,
    [property: Description("Terminal Verification Results — Bit 95, 10 hex chars (5 bytes).")] string Tvr,
    [property: Description("Transaction Currency Code — ISO 4217, 4 hex chars (e.g. \"0986\" = BRL).")] string CurrencyCode,
    [property: Description("Transaction Date in YYMMDD (e.g. \"250615\" = 2025-06-15).")] string TransactionDate,
    [property: Description("Transaction Type — 2 hex chars (e.g. \"00\" = purchase).")] string TransactionType,
    [property: Description("Unpredictable Number — 8 hex chars, generated by the terminal.")] string UnpredictableNumber,
    [property: Description("Application Interchange Profile — Bit 82, 4 hex chars.")] string Aip,
    [property: Description("Issuer Application Data — Bit 9F10, variable length (16–64 hex chars depending on scheme).")] string Iad,
    [property: Description("Brand profile: \"Visa\", \"Mastercard\" or \"Elo\".")] string Profile);

public sealed record GenerateArpcRequest(
    [property: Description("ARQC value calculated by the chip (16 hex chars / 8 bytes).")] string Arqc,
    [property: Description("Issuer Master Key, 32 hex chars (16 bytes).")] string IssuerMasterKey,
    [property: Description("PAN (13–19 digits).")] string Pan,
    [property: Description("PAN Sequence Number, 2 hex chars.")] string PanSequenceNumber,
    [property: Description("Application Transaction Counter, 4 hex chars.")] string Atc,
    [property: Description("Authorization Response Code — 4 hex chars representing the 2-char ASCII RC (e.g. \"3030\" → \"00\" = approved).")] string AuthResponseCode,
    [property: Description("Card Status Update (Method 2 only) — 8 hex chars. Pass null when using Method 1.")] string? Csu,
    [property: Description("Brand profile: \"Visa\", \"Mastercard\" or \"Elo\".")] string Profile,
    [property: Description("ARPC method: \"Method1\" (XOR-based — Visa / Elo) or \"Method2\" (CSU-based — Mastercard).")] string Method);

public sealed record BuildBit55ResponseRequest(
    string Arpc,
    string AuthResponseCode,
    string? IssuerAuthCode = null,
    string? IssuerScript71 = null,
    string? IssuerScript72 = null);

public sealed record FullFlowRequest(
    string HexBit55Request,
    string IssuerMasterKey,
    string Pan,
    string PanSequenceNumber,
    string AuthResponseCode,
    string Profile,
    string? IssuerScript71 = null,
    string? IssuerScript72 = null,
    string? IssuerAuthCode = null);

// ── Responses ───────────────────────────────────────────────────────────────

public sealed record TlvTagResponse(
    string Tag,
    string Name,
    int Length,
    string Value,
    string Description);

public sealed record ParseBit55Response(
    bool Success,
    List<TlvTagResponse> Tags,
    string? Arqc,
    string? CryptogramType,
    string? Atc,
    string? AuthResponseCode,
    bool HasArqc,
    bool HasIssuerAuthData,
    bool IsComplete,
    string? ParseError,
    int ParsedBytes,
    int TotalBytes,
    string? UnparsedHex,
    int? ErrorAtByte,
    List<string> Warnings,
    string? HeaderHex);

public sealed record ValidateArqcResponse(
    bool IsValid,
    string CalculatedArqc,
    string ReceivedArqc,
    List<TlvTagResponse> Tags,
    string Profile,
    string SessionKey);

public sealed record GenerateArqcResponse(
    string Arqc,
    string SessionKey,
    string IccMasterKey,
    string TransactionData,
    string Profile);

public sealed record GenerateArpcResponse(
    string Arpc,
    string Method,
    string SessionKey);

public sealed record BuildBit55ResponseResponse(
    string HexBit55,
    List<TlvTagResponse> Tags);

public sealed record FullFlowResponse(
    ValidateArqcResponse ArqcValidation,
    string Arpc,
    string HexBit55Response,
    List<TlvTagResponse> ResponseTags,
    string FlowSummary);
